# Generated by Django 3.2.5 on 2021-07-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_workassigned'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkAssigned',
            new_name='AssignedWork',
        ),
    ]
