# Generated by Django 3.2.5 on 2021-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_assignedwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skill_set',
            field=models.ManyToManyField(to='crm.Service'),
        ),
    ]
