# Generated by Django 3.2.5 on 2021-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_employee_skill_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skill_set',
            field=models.ManyToManyField(blank=True, related_name='Service', to='crm.Service'),
        ),
    ]
